AutomationTracker/AutomationTracker/Controllers/AssetController.cs
using AutomationTracker.Models;
using Postal;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Mvc;

namespace AutomationTracker.Controllers
{
    public class AssetController : Controller
    {
        OfficeAutomationdbEntities _context = new OfficeAutomationdbEntities();
        // GET: Asset

        public ActionResult Test()
        {
            var disposeList = _context.PhoneDongles.SqlQuery("Select * FROM dbo.PhoneDongles where DisposeDate<=DATEADD(m, 3, GETDATE()) and IsEmailSend = 0");

            dynamic email = new Postal.Email("DisposeEmail");
            email.To = "pavidsscst@gmail.com"; //objEmail.To;
            email.From = "pavithra@walkerstours.com";//objEmail.From;

            //if (objEmail.EmailBCC != null)
            //{
            //    email.Cc = objEmail.EmailCC;
            //}
            //if (objEmail.EmailCC != null)
            //{
            //    email.Bcc = objEmail.EmailBCC;
            //}

            email.DisposeList = disposeList;

            //return new EmailViewResult(email);
            email.Send();
            return new EmailViewResult(email);
        }


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewComputers()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            AssetList objModel = new AssetList();

            objModel.computerList = _context.Computers.Where(w=>w.IsActive == true).ToList();

            return View(objModel);
        }

        public ActionResult ManageComputers(int? id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            if (id > 0)
            {
                Computer computers = _context.Computers.Where(m => m.AUOTID == id).FirstOrDefault();
                if (computers != null)
                {
                    AssetModel objModel = new AssetModel();
                    AssetList objList = new AssetList();
                    objList.unittypeList = new List<UnitType>();
                    objList.unittypeList.Add(computers.UnitType1);

                    objList.modelList = new List<ModelType>();
                    objList.modelList.Add(computers.ModelType1);

                    objList.softwareList = new List<Software>();
                    objList.softwareList.Add(computers.Software);
                    objList.softwareList.Add(computers.Software1);

                    objList.companyList = new List<Company>();
                    objList.companyList.Add(computers.Company1);

                    objModel.assetList = objList;
                    objModel.computers = computers;
                    return View(objModel);
                }                
            }
            else
            {
                AssetModel objModel = new AssetModel();
                AssetList objList = new AssetList();
                objModel.computers = new Computer();
                objModel.computers.IsActive = true;

                objList.unittypeList = _context.UnitTypes.ToList();
                objList.softwareList = new List<Software>();
                objList.modelList = new List<ModelType>();
                objList.companyList = _context.Companies.ToList();

                objModel.assetList = objList;

                return View(objModel);
            }
            return null;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveComputers(AssetModel objModel)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            string _userName = Session["UserName"].ToString();

            try
            {
                if (objModel.computers.AUOTID == 0)
                {
                    try
                    {
                        Computer pc = new Computer();
                        pc.ModelType = objModel.computers.ModelType;
                        pc.UnitType = objModel.computers.UnitType;
                        pc.AssestNo = objModel.computers.AssestNo;
                        pc.SerialNo = objModel.computers.SerialNo;
                        pc.OS = objModel.computers.OS;
                        pc.OfficeVersion = objModel.computers.OfficeVersion;
                        pc.RAM = objModel.computers.RAM;
                        pc.HDDCapacity = objModel.computers.HDDCapacity;
                        pc.Remarks = objModel.computers.Remarks;
                        pc.Company = objModel.company.CompanyID;
                        pc.PurchaseDate = objModel.computers.PurchaseDate;
                        pc.DisposeDate = objModel.computers.DisposeDate;
                        pc.IsActive = true;
                        pc.WarrantyExpireDate = objModel.computers.WarrantyExpireDate;

                        pc.AddedBy = _userName;
                        pc.AddedDate = DateTime.Now;

                        _context.Computers.Add(pc);
                        _context.SaveChanges();

                        User _user = _context.Users.Where(w => w.FullName.Contains("IT Pool") && w.Company == objModel.company.CompanyID).FirstOrDefault();
                        UnitType _unitType = _context.UnitTypes.Where(w => w.UnitTypeID == pc.UnitType).FirstOrDefault();

                        UserAsset _userAssest = new UserAsset();
                        _userAssest.Category = _unitType.Category;
                        _userAssest.ItemID = pc.AUOTID;
                        _userAssest.PANo = _user.PANo;
                        _userAssest.UserID = _user.UserID;

                        _context.UserAssets.Add(_userAssest);
                        _context.SaveChanges();
                    }
                    catch (Exception ex)
                    {

                    }
                }
                else
                {
                    Computer pc = _context.Computers.Where(m => m.AUOTID == objModel.computers.AUOTID).FirstOrDefault();
                    pc.OS = objModel.computers.OS;
                    pc.OfficeVersion = objModel.computers.OfficeVersion;
                    pc.HDDCapacity = objModel.computers.HDDCapacity;
                    pc.Remarks = objModel.computers.Remarks;
                    pc.Company = objModel.company.CompanyID;

                    if (!objModel.computers.IsActive)
                    {
                        pc.IsActive = objModel.computers.IsActive;
                        pc.DisposeRemark = objModel.computers.DisposeRemark;

                        DisposeList _disposePC = new DisposeList();
                        _disposePC.Category = 1;
                        _disposePC.DisposeDate = pc.DisposeDate;
                        _disposePC.IsDisposed = true;
                        _disposePC.ItemID = pc.AUOTID;
                        _disposePC.UpdateBy = _userName;
                        _disposePC.UpdateDate = DateTime.Now;

                        _context.DisposeLists.Add(_disposePC);

                        var _assest = _context.UserAssets.Where(w => w.ItemID == pc.AUOTID && w.Category == 1).FirstOrDefault();

                        _context.UserAssets.Remove(_assest);
                        _context.SaveChanges();
                    }

                    pc.UpdateBy = _userName;
                    pc.UpdateDate = DateTime.Now;

                    //_context.Computers.Attach(pc);
                    //_context.Entry(pc).State = EntityState.Modified;
                    _context.SaveChanges();
                }
                return RedirectToAction("ViewComputers");
            }
            catch(DbEntityValidationException e)
            {
                Console.WriteLine(e);
                return null;
            }
        }

        public ActionResult ViewMobilePhones()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            AssetList objModel = new AssetList();

            objModel.phonesanddongleList = _context.PhoneDongles.Where(w => w.IsActive == true).ToList();

            return View(objModel);
        }

        public ActionResult ManageMobilePhones(int? id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Account");
            }

            if (id > 0)
            {
                PhoneDongle phones = _context.PhoneDongles.Where(m => m.AUOTID == id).FirstOrDefault();
                if (phones != null)
                {
                    AssetModel objModel = new AssetModel();
                    AssetList objList = new AssetList();
                    objList.unittypeList = new List<UnitType>();
                    objList.unittypeList.Add(phones.UnitType1);

                    objList.modelList = new List<ModelType>();
                    objList.modelList.Add(phones.ModelType1);
                    objList.providerList = new List<Provider>();
                    objList.providerList.Add(phones.Provider1);

                    objList.companyList = new List<Company>();
                    objList.companyList.Add(phones.Company1);

                    objModel.assetList = objList;
                    objModel.phonesanddongles = phones;
                    return View(objModel);
                }
            }
            else
            {
                AssetModel objModel = new AssetModel();
                AssetList objList = new AssetList();
                objModel.phonesanddongles = new PhoneDongle();
                objModel.phonesanddongles.IsActive = true;

                objList.unittypeList = _context.UnitTypes.ToList();

AutomationTracker/AutomationTracker/Views/Asset/DisposeList.cshtml
@model AutomationTracker.Models.AssetList
@{
    ViewBag.Title = "DisposeList";
    ViewBag.Menu = "DisposeList";
    Layout = "~/Views/Shared/_SystemLayout.cshtml";
}

<section class="common_section">
    <div class="container">

        @*<div class="container" style="padding-bottom:20px;">
                <input type="button" style="float:right;" class="btn btn-primary" value="Add Computer" onclick="location.href='@Url.Action("ManageComputers", "Asset", new { id = 0 })'" />
            </div>*@

        <h3 style="margin-bottom:20px;">
            <label class="labelcls">Dispose List </label>
        </h3>


        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#home">Computers & Laptops</a></li>
            <li><a data-toggle="tab" href="#menu1">Mobile Phones & Dongles</a></li>
            <li><a data-toggle="tab" href="#menu2">VOIP</a></li>
            <li><a data-toggle="tab" href="#menu3">Other</a></li>
        </ul>


        <div class="tab-content">
            <div id="home" class="tab-pane fade in active">
                <div style="margin-top:10px;">
                    <table id="computersTable" class="display nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Item ID</th>
                                <th>Unit Type Name</th>
                                <th>Model Name</th>
                                <th>Asset Number</th>
                                <th>Serial number</th>
                                <th>Dispose Date</th>
                                <th>Dispose Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.computerList.Count > 0)
                            {
                                foreach (var items in Model.computerList)
                                {
                                    <tr>
                                        <td>
                                            @items.AUOTID
                                        </td>
                                        <td>
                                            @items.UnitType1.UnitTypeName
                                        </td>
                                        <td>
                                            @items.ModelType1.ModelName
                                        </td>
                                        <td>
                                            @items.AssestNo
                                        </td>
                                        <td>
                                            @items.SerialNo
                                        </td>
                                        <td>
                                            @items.DisposeDate
                                        </td>
                                        <td>
                                            @items.DisposeRemark
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

            </div>
            <div id="menu1" class="tab-pane fade">
                <h3>Mobile Phones & Dongles</h3>
                <div style="margin-top:5px;">
                    <table id="mobilePhoneTable" class="display nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Item ID</th>
                                <th>Unit Type Name</th>
                                <th>Model Name</th>
                                <th>Asset Number</th>
                                <th>Serial number</th>
                                <th>Dispose Date</th>
                                <th>Dispose Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.phonesanddongleList.Count > 0)
                            {
                                foreach (var items in Model.phonesanddongleList)
                                {
                                    <tr>
                                        <td>
                                            @items.AUOTID
                                        </td>
                                        <td>
                                            @items.UnitType1.UnitTypeName
                                        </td>
                                        <td>
                                            @items.ModelType1.ModelName
                                        </td>
                                        <td>
                                            @items.AssestNo
                                        </td>
                                        <td>
                                            @items.SerialNo
                                        </td>
                                        <td>
                                            @items.DisposeDate
                                        </td>
                                        <td>
                                            @items.DisposeRemark
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="menu2" class="tab-pane fade">
                <h3>VOIP</h3>
                <div style="margin-top:10px;">
                    <table id="voipTable" class="display nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Item ID</th>
                                <th>Unit Type Name</th>
                                <th>Model Name</th>
                                <th>Asset Number</th>
                                <th>Serial number</th>
                                <th>Dispose Date</th>
                                <th>Dispose Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.voipList.Count > 0)
                            {
                                foreach (var items in Model.voipList)
                                {
                                    <tr>
                                        <td>
                                            @items.AUTOID
                                        </td>
                                        <td>
                                            @items.UnitType1.UnitTypeName
                                        </td>
                                        <td>
                                            @items.ModelType1.ModelName
                                        </td>
                                        <td>
                                            @items.AssestNo
                                        </td>
                                        <td>
                                            @items.SerialNo
                                        </td>
                                        <td>
                                            @items.DisposeDate
                                        </td>
                                        <td>
                                            @items.DisposeRemark
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="menu3" class="tab-pane fade">
                <h3>Other</h3>
                <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            </div>
        </div>

        </div>
</section>

@section scriptLocation{
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#computersTable').DataTable({
                dom: 'Bfrtip',
                "pagingType": "full_numbers",
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });

        $(document).ready(function () {
            $('#mobilePhoneTable').DataTable({
                dom: 'Bfrtip',
                "pagingType": "full_numbers",
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });

        $(document).ready(function () {
            $('#voipTable').DataTable({
                dom: 'Bfrtip',
                "pagingType": "full_numbers",
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });
    </script>
}

AutomationTracker/AutomationTracker/Views/Asset/ManageVOIP.cshtml
@model AutomationTracker.Models.AssetModel
@{
    ViewBag.Title = "ManageVOIP";
    ViewBag.Menu = "ViewVOIP";
    Layout = "~/Views/Shared/_SystemLayout.cshtml";
}

@using (Html.BeginForm("SaveVOIPDevices", "Asset"))
{
    @Html.AntiForgeryToken()

    <section class="common_section">
        <div class="container">

            @Html.HiddenFor(m => Model.voip.AUTOID)
            @Html.HiddenFor(m => Model.voip.Company)


            <div class="row">
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="dropUnitType" class="labelcls">Unit Type: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        <section class="col col-6">
                            <span id="spryUnitType">
                                @if (Model.voip.AUTOID > 0)
                                {
                                    @Html.DropDownListFor(m => Model.voip.UnitType, new SelectList(Model.assetList.unittypeList, "UnitTypeID", "UnitTypeName"), "- Please Select Unit type -", new
                               {
                                   @name = "dropUnitType",
                                   @class = "form-control",
                                   @disabled = "disabled",
                                   @id = "dropUnitType"
                               })
                                }
                                else
                                {
                                    @Html.DropDownListFor(m => Model.voip.UnitType, new SelectList(Model.assetList.unittypeList, "UnitTypeID", "UnitTypeName"), "- Please Select Unit type -", new
                               {
                                   @name = "dropUnitType",
                                   @class = "form-control",
                                   @id = "dropUnitType"
                               })
                                }
                                <span class="selectRequiredMsg">Please select an item.</span>
                            </span>
                        </section>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="dropModelType" class="labelcls">Model Type: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        <section class="col col-6">
                            <span id="spryModel">
                                @if (Model.voip.AUTOID > 0)
                                {
                                    @Html.DropDownListFor(m => Model.voip.ModelType, new SelectList(Model.assetList.modelList, "ModelID", "ModelName"), "- Please Select Model type -", new
                               {
                                   @name = "dropModel",
                                   @class = "form-control",
                                   @disabled = "disabled",
                                   @id = "dropModel"
                               })
                                }
                                else
                                {
                                    @Html.DropDownListFor(m => Model.voip.ModelType, new SelectList(Model.assetList.modelList, "ModelID", "ModelName"), "- Please Select Model type -", new
                               {
                                   @name = "dropModel",
                                   @class = "form-control",
                                   @id = "dropModel"
                               })
                                }
                                <span class="selectRequiredMsg">Please select an item.</span>
                            </span>
                        </section>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="txtAssestNo" class="labelcls">Assest No: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        <section>
                            <span id="spryAssestNo">
                                @Html.TextBoxFor(m => Model.voip.AssestNo, new
                           {
                               @name = "txtAssestNo",
                               @placeholder = "Assest No", @*@disabled = hiddenstyle,*@ @class = "form-control",
                               @id = "txtAssestNo"
                           })
                                <span class="textfieldRequiredMsg">A value is required.</span>
                            </span>
                        </section>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="txtSerialNo" class="labelcls">Serial No: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        <section>
                            <span id="sprySerialNo">
                                @Html.TextBoxFor(m => Model.voip.SerialNo, new
                           {
                               @name = "txtSerialNo",
                               @placeholder = "Serial No", @*@disabled = hiddenstyle,*@ @class = "form-control",
                               @id = "txtSerialNo"
                           })
                                <span class="textfieldRequiredMsg">A value is required.</span>
                            </span>
                        </section>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="txtExtentionNo" class="labelcls">Extention No: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        @Html.TextBoxFor(m => Model.voip.ExtentionNo, new { @name = "txtExtentionNo", @placeholder = "Extention No", @class = "form-control", @id = "txtExtentionNo" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="dropCompany" class="labelcls">Company: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        <section class="col col-6">
                            <span id="spryCompany">
                                @Html.DropDownListFor(m => Model.voip.Company1.CompanyID, new SelectList(Model.assetList.companyList, "CompanyID", "CompanyName"), "- Please Select Company -", new
                           {
                               @name = "dropCompany", @class = "form-control",
                               @id = "dropCompany"
                           })
                                <span class="selectRequiredMsg">Please select an item.</span>
                            </span>
                        </section>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="datetimepicker1" class="labelcls">Purchase Date: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        <section>
                            <span id="spryPurchaseDate">
                                @Html.TextBoxFor(m => Model.voip.PurchaseDate, new
                           {
                               @name = "datetimepicker1",
                               @placeholder = "Purchase Date", @*@disabled = hiddenstyle,*@ @class = "form-control",
                               @id = "datetimepicker1"
                           })
                                <span class="textfieldRequiredMsg">A value is required.</span>
                            </span>
                        </section>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class='input-container'>
                        <label for="datetimepicker2" class="labelcls">Dispose Date: </label>
                        <div class="icon-ph"><i class="icon-envelope"></i></div>
                        <section>
                            <span id="spryDisposeDate">
                                @Html.TextBoxFor(m => Model.voip.DisposeDate, new
                           {
                               @name = "datetimepicker2",
                               @placeholder = "Dispose Date", @*@disabled = hiddenstyle,*@ @class = "form-control",
                               @id = "datetimepicker2"
                           })
                                <span class="textfieldRequiredMsg">A value is required.</span>
                            </span>
                        </section>
                    </div>
                </div>
            </div>


            <div class='input-container'>
                <label for="txtRemarks" class="labelcls">Remarks: </label>
                <div class="icon-ph"><i class="icon-envelope"></i></div>
                @Html.TextAreaFor(m => Model.voip.Remarks, new { @name = "txtRemarks", @placeholder = "Remarks", @class = "form-control", @id = "txtRemarks" })
            </div>

            <div class='input-container'>
                <label for="chactive" class="labelcls">Active: </label>
                <div class="funkyradio">
                    <div class="funkyradio-success">
                        @if (Model.voip.AUTOID == 0)
                        {
                            @Html.CheckBoxFor(m => Model.voip.IsActive, new { @name = "checkbox", @disabled = "disabled", @checked = "checked", @id = "checkbox3" })
                        }
                        else
                        {
                            @Html.CheckBoxFor(m => Model.voip.IsActive, new { @name = "checkbox", @checked = "checked", @id = "checkbox3" })
                        }
                        <label for="checkbox3">Active</label>
                    </div>
                </div>
            </div>

            <div class='input-container' id="divDisposeRemark" style="display: none">
                <label for="txtDisposeRemarks" class="labelcls">Dispose Remarks: </label>
                <div class="icon-ph"><i class="icon-envelope"></i></div>
                @Html.TextAreaFor(m => Model.voip.DisposeRemark, new { @name = "txtDisposeRemarks", @placeholder = "Dispose Remarks", @class = "form-control", @id = "txtDisposeRemarks" })
            </div>

            <div style="margin-top:10px;">
                <button type="submit" class="btn btn-primary">Submit</button>

                <input type="button" style="margin-left:10px" class="btn btn-primary" value="Back" onclick="location.href='@Url.Action("ViewVOIP", "Asset")'" />
            </div>

        </div>
    </section>
                            }

@section scriptLocation{
<script src="~/js/Assest/ManageVOIP.js"></script>
<script src="~/build/jquery.datetimepicker.full.js"></script>
<script src="~/js/custom.js"></script>
}